title: "deKonvoluted"
symbol: "Ꮬ"
author: "Karthik Periagaram"
timezone: "America/Los_Angeles"
highlighter: pygments
encoding: "utf-8"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: "_posts/"
            type: "posts"
        values:
            layout: "post"


