defaults:
    -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
    -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"

encoding: "utf-8"
timezone: "America/Los_Angeles"
highlighter: pygments

